[package]
name = "nixos-utils"
version = "0.1.0"
authors = ["Alexander V. Nikolaev <avn@avnik.info>"]
publish = false

[lib]
name = "nixos_utils"

[dependencies]
atomicwrites = "0.2.2"
clap = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
pgs-files = "*"
